### ISSUE TITLE
Functions never called

### ISSUE THREAD

**Issue by richardMeggyes** [arteria/django-background-tasks#136]
Hi!

I tried it on Django 2.0.4 and i can see the jobs on the admin site, but they were never executed. I checked the time, tried to change it to see if the problem is some timezone difference, but nothing helped. Do you have any idea, what could be the problem? I read all issues in this repo.

**Comment by richardMeggyes** [comment]
I found out, that i used this extension wrong. I expected that the main process will execute the tasks, than i ran process_tasks and it worked.

**Comment by felocru** [comment]
Thanks to you, I was able to solve the problem, exactly the same thing was happening to me.
I think it is necessary to clarify much better that the Django process does not launch the tasks in subprocesses, it is necessary to execute the command so that the tasks are executed. I just believed that using the command was another way to execute them.

**Comment by walterrenner** [comment]
@felocru Thanks for your acknowledgement. Feel free to make changes to the documentation and sending a Pull request if you think that might help other people as well.
