### ISSUE TITLE
Clear old tasks 

### ISSUE THREAD

**Issue by locvx1234** [arteria/django-background-tasks#141]
When I don't call the function below @background decorator, it still runs repeatedly. I previously called that function with the repeat argument. 
p/s : I've kill process : `python manage.py process_tasks` and run again.

I think the tasks are still saved. can you tell me how to clear them?  
tks~!

**Comment by davidzwa** [comment]
I think manually deleting them from the database will fix your problem. Becuase the process_tasks command also queries the database constantly and will not see deleted tasks anymore.

You can also manually add them to completed tasks, although it doesn't seem required.

**Comment by Ericwonne** [comment]
For me, using django-background-tasks 1.2.5.
Because in my code the repeat is set to 1 and repeat_until is None, so after some while, the completed_task database will be huge and cluttered. If I want to delete the completed_task in my code, I'd use:

from background_task.models import CompletedTask
CompletedTask.objects.all().delete()
