### ISSUE TITLE
run the tasks asynchronous

### ISSUE THREAD

**Issue by MinhKMA** [arteria/django-background-tasks#148]
I want to run background tasks at the same time, option `BACKGROUND_TASK_RUN_ASYNC` = `True` but i am having a problem and i can not run it . Can you help me?

**Comment by philippeowagner** [comment]
Could you provide more information? 
Is the process running?

**Comment by philippeowagner** [comment]
Closing this due to no update.

**Comment by pssolanki111** [comment]
@philippeowagner Hey there phillip, thanks for this wonderful lib.

I have an issue with the `BACKGROUND_TASK_RUN_ASYNC`. 

I did a test with it set to false in the first go, which of course executed the tasks linearly. 

I changed it to be `True` and it still executed the two tasks linearly one after another instead of doing it async.

Django version: `3.2.6` (latest)
python version: `3.8` 
dj-vbg-tasks version: `1.2.5` (latest)

the task is a simple function which just print the argument passed to it.

both tasks are scheduled for almost the same time with a couple second's difference

Happy to provide more info if needed.

Any help is appreciated :)
