### ISSUE TITLE
My tasks are being randomly locked and never unlocked.

### ISSUE THREAD

**Issue by IliyanTatarov** [arteria/django-background-tasks#177]
I am using the django-background-tasks 1.2.0 on Ubuntu 18.04 and Im running it with a cronjob. Is it possible that my cronjob somehow starts the tasks right before it is refreshed and then it gets stuck ?
I could get one or many stuck tasks from the same moment.

Cronjob:
* * * * *  /project/manage.py process_tasks --duration=59 --sleep=2

settings.py
BACKGROUND_TASK_RUN_ASYNC = True
BACKGROUND_TASK_ASYNC_THREADS = 4

**Comment by MajorClod** [comment]
I experienced something similar tonight when testing the ASYNC functionality.  What I was finding is that if i had process_tasks running in a process, refreshing the task list via Django Admin (so I could check which tasks were running) would actually cause any currently running tasks to immediately stop (and remain "locked")

**Comment by philippeowagner** [comment]
What happens if your run `./manage.py process_tasks` w/o duration and sleep?

**Comment by Moondog360** [comment]
any update on this I am running into a similar issue. when running it with or without duration/sleep. The process_task crashes with a `Transaction (Process ID 58) was deadlocked on lock resources with another process and has been chosen as the deadlock victim.` message. But this only happens if I am viewing the Tasks view in admin. And when `BACKGROUND_TASK_RUN_ASYNC` is set to `True`

**Comment by philippeowagner** [comment]
Are you using SQLite? Is so check https://django-background-tasks.readthedocs.io/en/latest/#known-issues. 

Please reopen it the error still persists.
