### ISSUE TITLE
duration handling / docs

### ISSUE THREAD

**Issue by benzkji** [arteria/django-background-tasks#189]
I wonder what happens to a task that is still executing, after a ./manage.py process_tasks --duration=x has officialy passed duration? will it be executed to the end, and only then, the process_tasks will exit? Wether yes or not, this would be nice to point out in the docs...would PR if got the infos ;-)

**Comment by benzkji** [comment]
my experience is: a longer taking tasks is killed, after duration has passed. beware if your tasks could take a long time.

**Comment by philippeowagner** [comment]
#142

**Comment by philippeowagner** [comment]
https://github.com/arteria/django-background-tasks/blob/a9ee7a59add089ce3561f4edbd22f5f5e4d4a5ff/background_task/management/commands/process_tasks.py#L89

The task in execution will be terminated because the main process is exiting in this case.

Task running longer than MAX_RUN_TIME will be restarted. 

We do not run the BGTs in cron processing mode. We let the process up and running using supervisor/daemon tools.  OK? Please reopen if needed.

**Comment by benzkji** [comment]
thanks! question answered. I've long running tasks, so I set cron to restart only once a day, during the night...not perfect yet, but working...

**Comment by philippeowagner** [comment]
So you have to assume that nothing is running in the night when you restart the service.
Why not use http://supervisord.org/ ? Is restarts only the process if it gets killed for some reasons. We use this since years in production...

**Comment by benzkji** [comment]
We also experimented with systemd...I just need the time to dig into ;-) also, it depends on hosting and server environments...and cron will always be there. but supervisor looks more convienient than systemd, on first sight...thanks for the suggestion!
