### ISSUE TITLE
Runner confuses tasks that have same name and parameters

### ISSUE THREAD

**Issue by jvamvas** [arteria/django-background-tasks#36]
When you try to schedule two tasks based on the same function with the same args/kwargs combination, only the first task will be executed. This happens even if the first task has exceeded its maximum of allowed attempts.

The following test fails with the current version of django-background-tasks.

``` python
from django.conf import settings
from django.test import TestCase

from background_task.tasks import tasks
from background_task.models import Task

class MultipleFailingTasksTestCase(TestCase):

    def setUp(self):
        @tasks.background(name='failing task')
        def failing_task():
            return 0/0
        self.failing_task = failing_task

    def test_multiple_failing_tasks(self):
        with self.settings(MAX_ATTEMPTS=1):
            self.assertEqual(settings.MAX_ATTEMPTS, 1)
            task1 = self.failing_task()
            task2 = self.failing_task()
            task1_id = task1.id
            task2_id = task2.id

            tasks.run_next_task()
            self.assertEqual(Task.objects.get(pk=task1_id).attempts, 1, 'task1 should have been executed')
            self.assertTrue(Task.objects.get(pk=task1_id).attempts >= settings.MAX_ATTEMPTS, 'task1 should have reached his maximum attempts')

            tasks.run_next_task()
            # Fails
            self.assertEqual(Task.objects.get(pk=task1_id).attempts, 1, 'task1 should not be executed anymore')
            # Fails
            self.assertEqual(Task.objects.get(pk=task2_id).attempts, 1, 'task2 should have been executed')
            # Fails
            self.assertTrue(Task.objects.get(pk=task2_id).attempts >= settings.MAX_ATTEMPTS, 'task2 should have reached his maximum attempts')

            tasks.run_next_task()
            # Fails
            self.assertEqual(Task.objects.get(pk=task1_id).attempts, 1, 'task1 should not be executed anymore')
            # Fails
            self.assertEqual(Task.objects.get(pk=task2_id).attempts, 1, 'task2 should not be executed anymore')
```

The issue seems to be caused by the fact that the SHA-1 hash used to identify tasks is based only on the task's name and parameters.

**Comment by jvamvas** [comment]
Partially resolved by 3844a3a.
Tasks are now turned into CompletedTask instances when they have exceeded MAX_ATTEMPTS. Thus, the problem described above will only occur if MAX_ATTEMPTS is set to a value greater than 1.

**Comment by december1981** [comment]
This issue was causing me problems when I had two identical tasks (same name and parameters), with one scheduled to begin later than the first.

The scheduler would find the earlier task, lock it, then in bg_runner, it would find the first match in Task.objects.get_task and run that. Well, that first match was sometimes the unlocked task that was supposed to be run at a later time.

End result was a task that is locked and never executed, and a delayed task that is immediately executed and not locked.

I found this issue in 1.0.7, and upgrading to 1.0.11 seems to fix it - but it could just be a fluke due to however the order comes out... or has this been resolved?

(A quick fix for me was just to run over all the results in Task.objects.get_task and select the one which had a locked status.)

**Comment by walterrenner** [comment]
@jvamvas i just ran an updated version of your test. this seems to be fixed.
