### ISSUE TITLE
AttributeError: module 'signal' has no attribute 'SIGTSTP'

### ISSUE THREAD

**Issue by hamza-jutt** [arteria/django-background-tasks#96]
When i tried to run `python manage.py process_tasks` I got an error.
`AttributeError: module 'signal' has no attribute 'SIGTSTP'`

Stack Trace:
File "D:\ENV\lib\site-packages\background_task\management\commands\process_tasks.py", line 80, in handle
    sig_manager = SignalManager()
  File "D:\ENV\lib\site-packages\background_task\utils.py", line 15, in __init__
    signal.signal(signal.SIGTSTP, self.exit_gracefully)
AttributeError: module 'signal' has no attribute 'SIGTSTP'

**Comment by kherrett** [comment]
I noticed this as well. You must be running on Windows? I'm doing development and testing on Windows, but plan to deploy my app on a Linux host. For the time being (in a pinch), you can adjust line 15 in background_task\utils.py from
`signal.signal(signal.SIGTSTP, self.exit_gracefully)`
to
`signal.signal(signal.SIGTERM, self.exit_gracefully)`
and then comment out the speed_up, slow_down, and SIGUSR1, SIGUSR2 lines, since Windows doesn't support those hooks.

If you deploy on a Linux host remember to change it back so you don't lose that functionality.

**Comment by philippeowagner** [comment]
This is absolutely a Windows related Issue. Not all signals are available on Windows, but [there are some](https://docs.python.org/2/library/signal.html#module-signal). 

This is under our radar, because we are working on Posix systems only. 

But yes – this should work on windows too. Help is welcomed to make this portable, the sooner the better.

**Comment by kherrett** [comment]
`# -*- coding: utf-8 -*-
import signal
import platform

TTW_SLOW = [0.5, 1.5]
TTW_FAST = [0.0, 0.1]


class SignalManager(object):
    """Manages POSIX signals."""

    kill_now = False
    time_to_wait = TTW_SLOW

    def __init__(self):
        # Temporary workaround for signals not available on Windows
        if platform.system() == 'Windows':
            signal.signal(signal.SIGTERM, self.exit_gracefully)
        else:
            signal.signal(signal.SIGTSTP, self.exit_gracefully)
            signal.signal(signal.SIGUSR1, self.speed_up)
            signal.signal(signal.SIGUSR2, self.slow_down)

    def exit_gracefully(self, signum, frame):
        self.kill_now = True

    def speed_up(self, signum, frame):
        self.time_to_wait = TTW_FAST

    def slow_down(self, signum, frame):
        self.time_to_wait = TTW_SLOW
`

**Comment by kherrett** [comment]
```python
# -*- coding: utf-8 -*-
import signal
import platform

TTW_SLOW = [0.5, 1.5]
TTW_FAST = [0.0, 0.1]


class SignalManager(object):
    """Manages POSIX signals."""

    kill_now = False
    time_to_wait = TTW_SLOW

    def __init__(self):
        # Temporary workaround for signals not available on Windows
        if platform.system() == 'Windows':
            signal.signal(signal.SIGTERM, self.exit_gracefully)
        else:
            signal.signal(signal.SIGTSTP, self.exit_gracefully)
            signal.signal(signal.SIGUSR1, self.speed_up)
            signal.signal(signal.SIGUSR2, self.slow_down)

    def exit_gracefully(self, signum, frame):
        self.kill_now = True

    def speed_up(self, signum, frame):
        self.time_to_wait = TTW_FAST

    def slow_down(self, signum, frame):
        self.time_to_wait = TTW_SLOW

```
